### ISSUE TITLE
seeMessageFrom now wants the name.

### ISSUE THREAD

**Issue by lukasoppermann** [tightenco/mailthief#51]
Hey,

I want to test the name & email of the sender.

However doing this:

``` php
$this->seeMessageFrom(config('mail.from.address'));
```

results in an error, because it actually checks gets the `config('mail.from.name')` part.

How can I check that name & email are correct?

**Comment by besologic** [comment]
For now you'll need to do something like: https://github.com/tightenco/mailthief/blob/master/tests/MailThiefTest.php#L404. Since you're using the testing trait, here's a README on how to fire up MailThief manually so you can get the underlying $mailer: https://github.com/tightenco/mailthief/blob/478f33ecce3e97ab4d0238db9b801d8071dad6a8/readme.md

I believe this is a bug from #42. @gpopoteur, do you want to take a pass at fixing this? I have a failing test on this branch: https://github.com/tightenco/mailthief/tree/fix-see-message-from-global-from-support. If not, let us know and we'll try to get in a fix soon.

**Comment by besologic** [comment]
Notes after doing some testing: pretty sure this has to do with the fact that when we store the global from information, we store the from information as an associative array `['the-email@example.com' => 'Example Name']. `seeMessageFrom` fails because it's comparing this array to the passed in email string. The fix that comes to mind is to add an optional parameter to `seeMessageFrom` taking in a name, and when appropriate, comparing both the email address and the name. If `seeMessageFrom` only takes in the email, it should successfully pass too.

**Comment by gpopoteur** [comment]
@besologic I'm able to fix this later today, if you guys already found a solution feel free to fix it 😄 👍
